// Offline support. Cache-first: the app has no content that goes stale on its own, and
// it must work with no network at all. Every path is relative to this file, which sits
// at the site root so its scope covers the whole app under the Pages subpath.
//
// The version and file list below are generated from the site files by
// tools/build-sw.mjs (npm run sw); lint fails if they are stale.

// BEGIN GENERATED by tools/build-sw.mjs
const VERSION = 'e96c378b276d';
const FILES = [
  './',
  './css/app.css',
  './css/tokens.css',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon.svg',
  './icons/maskable-512.png',
  './index.html',
  './js/audio/context.js',
  './js/audio/instruments.js',
  './js/audio/scheduler.js',
  './js/drills/adaptive.js',
  './js/drills/cadence.js',
  './js/drills/chapters.js',
  './js/drills/chord.js',
  './js/drills/degree.js',
  './js/drills/interval.js',
  './js/drills/inversion.js',
  './js/drills/melody.js',
  './js/drills/note.js',
  './js/drills/phrase.js',
  './js/drills/progression.js',
  './js/drills/registry.js',
  './js/drills/scale.js',
  './js/drills/trial.js',
  './js/i18n/en.json',
  './js/i18n/es.json',
  './js/i18n/index.js',
  './js/jam/engine.js',
  './js/jam/midi-export.js',
  './js/labels.js',
  './js/main.js',
  './js/state/backup.js',
  './js/state/migrate.js',
  './js/state/store.js',
  './js/theory/chords.js',
  './js/theory/harmony.js',
  './js/theory/pitch.js',
  './js/theory/scales.js',
  './js/ui/grid.js',
  './js/ui/hud.js',
  './js/ui/jam-view.js',
  './js/ui/keyboard.js',
  './js/ui/practice.js',
  './js/ui/reference.js',
  './js/ui/sequence.js',
  './js/ui/settings.js',
  './js/ui/shortcuts.js',
  './js/ui/stages.js',
  './js/ui/stats.js',
  './js/ui/update.js',
  './js/util.js',
  './manifest.webmanifest',
];
// END GENERATED

const CACHE = 'ear-' + VERSION;

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)));
  // No skipWaiting() here: swapping the worker under a session with audio scheduled is
  // worse than waiting. The page offers a reload and posts SKIP_WAITING on accept.
});

self.addEventListener('message', e => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches
      .keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('ear-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  e.respondWith(
    caches.open(CACHE).then(async c => {
      const hit = await c.match(req, { ignoreSearch: true });
      if (hit) return hit;
      try {
        return await fetch(req);
      } catch (err) {
        // Offline deep link or reload: serve the app shell.
        if (req.mode === 'navigate') return c.match('./index.html');
        throw err;
      }
    }),
  );
});
