import { WHITE, ALL12, ALLIVL } from '../theory/pitch.js';
import { SC } from '../theory/scales.js';
import { PROG_25, PROG_BASIC, PROG_BORROW } from '../theory/harmony.js';

// The stage ladder. k: drill kinds, n: questions per run, limit: seconds per answer.
export const CHAPTERS = [
  {
    t: 'A \u00b7 Pitch',
    st: [
      { t: 'Two anchors', k: ['note'], pcs: [0, 6], oct: [4, 4], n: 12 },
      { t: 'Three anchors', k: ['note'], pcs: [0, 4, 8], oct: [4, 4], n: 14 },
      { t: 'Four anchors', k: ['note'], pcs: [0, 3, 6, 9], oct: [4, 4], n: 16 },
      { t: 'White keys', k: ['note'], pcs: WHITE, oct: [4, 4], n: 18 },
      { t: 'All twelve', k: ['note'], pcs: ALL12, oct: [4, 4], n: 20, limit: 12 },
      { t: 'Across octaves', k: ['note'], pcs: ALL12, oct: [3, 5], n: 20, limit: 10 },
      { t: 'Shifting timbre', k: ['note'], pcs: ALL12, oct: [2, 6], n: 20, limit: 9, timbre: 'mixed' },
      { t: 'Name the octave', k: ['note'], pcs: ALL12, oct: [3, 5], reqOct: true, n: 18, limit: 12 },
    ],
  },
  {
    t: 'B \u00b7 Intervals',
    st: [
      { t: 'Fourths & fifths', k: ['interval'], ivls: [5, 7, 12], dir: 'asc', oct: [3, 5], n: 14 },
      { t: 'Thirds & sixths', k: ['interval'], ivls: [3, 4, 8, 9], dir: 'asc', oct: [3, 5], n: 16 },
      { t: 'Seconds & sevenths', k: ['interval'], ivls: [1, 2, 10, 11], dir: 'asc', oct: [3, 5], n: 16 },
      { t: 'Every interval up', k: ['interval'], ivls: ALLIVL, dir: 'asc', oct: [3, 5], n: 20, limit: 10 },
      { t: 'Up and down', k: ['interval'], ivls: ALLIVL, dir: 'random', oct: [3, 5], n: 20, limit: 10 },
      { t: 'Played together', k: ['interval'], ivls: ALLIVL, dir: 'harm', oct: [3, 5], n: 18, limit: 10 },
    ],
  },
  {
    t: 'C \u00b7 Chords',
    st: [
      { t: 'Major or minor', k: ['chord'], chords: ['maj', 'min'], oct: [3, 4], n: 14 },
      { t: 'Add dim and aug', k: ['chord'], chords: ['maj', 'min', 'dim', 'aug'], oct: [3, 4], n: 16 },
      { t: 'Suspensions', k: ['chord'], chords: ['maj', 'min', 'sus4', 'sus2'], oct: [3, 4], n: 16 },
      { t: 'Triad inversions', k: ['inv'], chords: ['maj', 'min'], invs: [0, 1, 2], oct: [3, 4], n: 16 },
      { t: 'Three sevenths', k: ['chord'], chords: ['maj7', 'dom7', 'min7'], oct: [3, 4], n: 18 },
      {
        t: 'The full seven',
        k: ['chord'],
        chords: ['maj7', 'dom7', 'min7', 'm7b5', 'dim7', 'mMaj7', 'min6'],
        oct: [3, 4],
        n: 20,
        limit: 12,
      },
      {
        t: 'Extensions',
        k: ['chord'],
        chords: ['dom7', 'dom9', 'maj7', 'maj9', 'min7', 'min9', 'd7b9'],
        oct: [3, 4],
        n: 20,
        limit: 12,
      },
      {
        t: 'Seventh inversions',
        k: ['inv'],
        chords: ['dom7', 'maj7', 'min7'],
        invs: [0, 1, 2, 3],
        oct: [3, 4],
        n: 20,
        limit: 12,
      },
      {
        t: 'Chords, arpeggiated',
        k: ['chord'],
        chords: ['maj', 'min', 'dim', 'aug', 'maj7', 'dom7', 'min7', 'm7b5'],
        arp: 1,
        oct: [3, 4],
        n: 20,
        limit: 10,
      },
    ],
  },
  {
    t: 'D \u00b7 Function',
    st: [
      { t: 'Degrees 1 3 5', k: ['degree'], degrees: [0, 2, 4], n: 14 },
      { t: 'Degrees 1 2 3 5 6', k: ['degree'], degrees: [0, 1, 2, 4, 5], n: 16 },
      { t: 'All seven', k: ['degree'], degrees: [0, 1, 2, 3, 4, 5, 6], n: 20, limit: 10 },
      { t: 'Seven in any key', k: ['degree'], degrees: [0, 1, 2, 3, 4, 5, 6], keyMode: 'random', n: 20, limit: 10 },
      {
        t: 'Minor key degrees',
        k: ['degree'],
        degrees: [0, 1, 2, 3, 4, 5, 6],
        keyQual: 'min',
        keyMode: 'random',
        n: 20,
        limit: 10,
      },
      { t: 'Cadences', k: ['cadence'], n: 14 },
      { t: 'ii V I spotting', k: ['prog'], progs: PROG_25, n: 12, limit: 0 },
      { t: 'Four-chord loops', k: ['prog'], progs: PROG_BASIC, n: 12 },
      { t: 'Borrowed chords', k: ['prog'], progs: PROG_BORROW, n: 12 },
      { t: 'Melody, 3 notes', k: ['melody'], melLen: 3, n: 12 },
      { t: 'Melody, 5 notes', k: ['melody'], melLen: 5, n: 12 },
      { t: 'Melody, any key', k: ['melody'], melLen: 5, keyMode: 'random', n: 12 },
    ],
  },
  {
    t: 'E \u00b7 Scales',
    st: [
      { t: 'Major or minor', k: ['scale'], scales: ['ionian', 'aeolian'], n: 12 },
      {
        t: 'Church modes',
        k: ['scale'],
        scales: ['ionian', 'dorian', 'phrygian', 'lydian', 'mixolydian', 'aeolian'],
        n: 18,
        limit: 12,
      },
      { t: 'Pentatonic & blues', k: ['scale'], scales: ['majPent', 'minPent', 'blues', 'ionian'], n: 14 },
      { t: 'Altered minors', k: ['scale'], scales: ['aeolian', 'harmMinor', 'melMinor', 'dorian'], n: 16, limit: 12 },
      { t: 'Everything', k: ['scale'], scales: Object.keys(SC), n: 20, limit: 14 },
    ],
  },
  {
    t: 'F \u00b7 Combined',
    st: [
      {
        t: 'Notes and intervals',
        k: ['note', 'interval'],
        pcs: ALL12,
        ivls: ALLIVL,
        dir: 'random',
        oct: [3, 5],
        n: 24,
        limit: 9,
      },
      {
        t: 'Chords and degrees',
        k: ['chord', 'degree'],
        chords: ['maj', 'min', 'dim', 'maj7', 'dom7', 'min7'],
        degrees: [0, 1, 2, 3, 4, 5, 6],
        n: 24,
        limit: 12,
      },
      {
        t: 'The lot',
        k: ['note', 'interval', 'chord', 'degree', 'scale'],
        pcs: ALL12,
        ivls: ALLIVL,
        dir: 'random',
        chords: ['maj', 'min', 'maj7', 'dom7', 'min7', 'm7b5'],
        degrees: [0, 1, 2, 3, 4, 5, 6],
        scales: ['ionian', 'dorian', 'mixolydian', 'aeolian'],
        oct: [3, 5],
        n: 30,
        limit: 12,
        timbre: 'mixed',
      },
    ],
  },
];
