// Writes the precache list and a content hash into sw.js. Run after changing any site
// file (npm run sw); `--check` fails when sw.js is stale, and lint runs it.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { siteFiles } from './site.mjs';

const files = siteFiles().filter(f => f !== 'sw.js' && f !== '.nojekyll');
const hash = createHash('sha256');
for (const f of files) hash.update(f + '\0').update(readFileSync(f));
const version = hash.digest('hex').slice(0, 12);

const src = readFileSync('sw.js', 'utf8');
const block =
  '// BEGIN GENERATED by tools/build-sw.mjs\n' +
  `const VERSION = '${version}';\n` +
  'const FILES = [\n' +
  ['./', ...files.map(f => './' + f)].map(f => `  '${f}',\n`).join('') +
  '];\n' +
  '// END GENERATED';
const out = src.replace(/\/\/ BEGIN GENERATED[\s\S]*?\/\/ END GENERATED/, block);

if (process.argv.includes('--check')) {
  if (out !== src) {
    console.error('sw.js is stale: run npm run sw');
    process.exit(1);
  }
} else writeFileSync('sw.js', out);
